### ISSUE TITLE
pip install: No module named '_itkIndexPython' - no attribute 'swig'

### ISSUE THREAD

**Issue by rfortiz** [InsightSoftwareConsortium/ITKMontage#163]
I'm trying to install the python package by running `pip install itk-montage` in a fresh conda environment with Python 3.7.7 under ubuntu 18.04. The installation seems to work and I get:

```bash
>>> import itk
>>> dir(itk.Montage)

['DataObjectDecorator', 'Image', 'ImageSource', 'ImageToImageFilter', 
'MaxPhaseCorrelationOptimizer', 'MaxPhaseCorrelationOptimizerEnums', 
'NMinimaMaximaImageCalculator', 
'PhaseCorrelationImageRegistrationMethod', 
'PhaseCorrelationImageRegistrationMethodEnums', 
'PhaseCorrelationOperator', 'PhaseCorrelationOptimizer', 
'SimpleDataObjectDecorator', 'Tile', 'TileConfiguration', 
'TileMergeImageFilter', 'TileMontage', 
'_LazyITKModule__belong_lazy_attributes', '__doc__', '__loader__', 
'__name__', '__package__', '__spec__', 'image_source', 
'image_to_image_filter', 'lazy_attributes', 'loaded_lazy_modules', 
'max_phase_correlation_optimizer', 
'phase_correlation_image_registration_method', 
'phase_correlation_operator', 'phase_correlation_optimizer', 
'tile_merge_image_filter', 'tile_montage', 'vector']
```

But then I'm not sure how to use it (any python example?) and I start to encounter errors:

```bash
>>> itk.Montage.TileMontage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[minicondaenv]/lib/python3.7/site-packages/itkLazy.py", line 52, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "[minicondaenv]/lib/python3.7/site-packages/itkBase.py", line 99, in LoadModule
    module = loader.load(swig_module_name)
  File "[minicondaenv]/lib/python3.7/site-packages/itkBase.py", line 220, in load
    module.__loader__.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "[minicondaenv]/lib/python3.7/site-packages/itk/MontagePython.py", line 113, in <module>
    from itkPhaseCorrelationOperatorPython import *
  File "[minicondaenv]/lib/python3.7/site-packages/itk/Configuration/../itkPhaseCorrelationOperatorPython.py", line 106, in <module>
    import itkIndexPython
  File "[minicondaenv]/lib/python3.7/site-packages/itk/Configuration/../itkIndexPython.py", line 15, in <module>
    import _itkIndexPython
ModuleNotFoundError: No module named '_itkIndexPython'
```
and if I try a second time (or try to use something else):

```bash
>>> itk.Montage.TileMontage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[minicondaenv]/lib/python3.7/site-packages/itkLazy.py", line 52, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "[minicondaenv]/lib/python3.7/site-packages/itkBase.py", line 61, in LoadModule
    swig.update(this_module.swig)
AttributeError: module 'itk.MontagePython' has no attribute 'swig'
```
Installing the main itk package first with conda manager `conda install -c conda-forge itk` results in the same error. 

The installation instructions are not very clear, so I assumed that `pip install itk-montage` is all I need and build instructions that come after refer to an alternative installation method: 

> To build the C++ module, either enable the CMake option in ITK's build configuration

Is it correct? Else what am I missing and where is the build configuration file?

**Comment by thewtex** [comment]
We need to update the Python package for changes in the recently release itk-5.1.

I am working on a few examples.

**Comment by thewtex** [comment]
```
python -m pip install --upgrade itk-montage
```
will address the import errors.

**Comment by rfortiz** [comment]
`python -m pip install --upgrade itk-montage` did not change anything. However with `--force-reinstall` or a fresh install I now get a different error:

```bash
>>> import itk
>>> itk.Montage.TileMontage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[minicondaenv]/lib/python3.7/site-packages/itkLazy.py", line 52, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "[minicondaenv]/lib/python3.7/site-packages/itkBase.py", line 99, in LoadModule
    module = loader.load(swig_module_name)
  File "[minicondaenv]/lib/python3.7/site-packages/itkBase.py", line 220, in load
    module.__loader__.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "[minicondaenv]/lib/python3.7/site-packages/itk/MontagePython.py", line 113, in <module>
    from itkPhaseCorrelationOperatorPython import *
  File "[minicondaenv]/lib/python3.7/site-packages/itk/Configuration/../itkPhaseCorrelationOperatorPython.py", line 106, in <module>
    import itkIndexPython
  File "[minicondaenv]/lib/python3.7/site-packages/itk/Configuration/../itkIndexPython.py", line 8, in <module>
    from . import _ITKCommonPython
ImportError: attempted relative import with no known parent package
```

and on second call the same 'swig' missing attribute as before.

**Comment by thewtex** [comment]
Is this reproducible in a fresh conda environment?

**Comment by thewtex** [comment]
Ah, it seems the package did not get deployed properly, and the dependencies are not strict enough to pull in the required `itk` package version. I will re-release and follow up.

**Comment by rfortiz** [comment]
yes the error was the same in a fresh conda environment. Now with itk-montage 0.5.1 just released on pypi and after manual install of missing numpy dependency:

```
>>> import itk
>>> itk.Montage.TileMontage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[minicondaenv]/envs/montage/lib/python3.8/site-packages/itkLazy.py", line 52, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "[minicondaenv]/envs/montage/lib/python3.8/site-packages/itkBase.py", line 99, in LoadModule
    module = loader.load(swig_module_name)
  File "[minicondaenv]/envs/montage/lib/python3.8/site-packages/itkBase.py", line 220, in load
    module.__loader__.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "[minicondaenv]/envs/montage/lib/python3.8/site-packages/itk/MontagePython.py", line 75, in <module>
    from itk.itkPhaseCorrelationOperatorPython import *
  File "[minicondaenv]/envs/montage/lib/python3.8/site-packages/itk/itkPhaseCorrelationOperatorPython.py", line 437, in <module>
    @itkHelpers.accept_numpy_array_like
AttributeError: module 'itkHelpers' has no attribute 'accept_numpy_array_like'
```

**Comment by thewtex** [comment]
`itk-montage` version `0.5.3` is now available, pulling in the `numpy` requirement and fixing this error.

**Comment by rfortiz** [comment]
It's now working, thanks. As far as installation goes, this issue can be closed. 

Usage remains a mystery to me though. Can it be used with loaded numpy arrays (converted to itkImage) or only through a TileConfiguration.txt file?

**Comment by thewtex** [comment]
Thanks for the feedback. It can work on images in NumPy arrays. I'll follow up here after we have a few examples.

**Comment by dzenanz** [comment]
Example added via #184.
